name = "NGWP"
uuid = "b1502bba-cf73-4b59-9b37-fa50c4aa0169"
authors = ["Haotian Li"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
